services:
  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy-conf:/etc/caddy
      - ./data/caddy-data:/data
    restart: always
    networks:
      - proxy

  warp:
    build:
      context: docker
      dockerfile: warp.Dockerfile
    mem_reservation: 128m
    mem_limit: 256m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/cloudflare-warp:/var/lib/cloudflare-warp
    restart: always
    networks:
      - proxy

  ss_direct:
    build:
      context: docker
      dockerfile: shadowsocks.Dockerfile
    user: "65534:65534"
    volumes:
      - ./data/shadowsocks-direct:/etc/shadowsocks-rust
    restart: always
    networks:
      - proxy

  ss_warp:
    build:
      context: docker
      dockerfile: shadowsocks.Dockerfile
    user: "65534:65534"
    network_mode: service:warp
    volumes:
      - ./data/shadowsocks-warp:/etc/shadowsocks-rust
    restart: always
    depends_on:
      - warp

  gost_direct:
    image: gogost/gost:3
    user: "65534:65534"
    entrypoint: ["gost"]
    command: ["-C", "/etc/gost/gost.yaml"]
    volumes:
      - ./data/gost-direct:/etc/gost
    restart: always
    networks:
      - proxy

  gost_warp:
    image: gogost/gost:3
    user: "65534:65534"
    entrypoint: ["gost"]
    command: ["-C", "/etc/gost/gost.yaml"]
    network_mode: service:warp
    volumes:
      - ./data/gost-warp:/etc/gost
    restart: always
    depends_on:
      - warp

networks:
  proxy:
