services:
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Volumes/caddyconf:/etc/caddy
      - ./Volumes/caddydata:/data
    restart: always
    networks:
      - proxy

  shadowsocks-direct:
    image: shadowsocks
    build:
      context: docker
      dockerfile: shadowsocks.Dockerfile
    container_name: shadowsocks-direct
    volumes:
      - ./Volumes/shadowsocks-direct:/etc/shadowsocks-rust
    restart: always
    networks:
      - proxy

  warp-shadowsocks:
    image: cloudflare-warp-shadowsocks
    build:
      context: docker
      dockerfile: warp-shadowsocks.Dockerfile
    container_name: warp-shadowsocks
    mem_reservation: 128m
    mem_limit: 320m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./Volumes/warp-shadowsocks:/var/lib/cloudflare-warp
    restart: always
    networks:
      - proxy

  shadowsocks-warp:
    image: shadowsocks
    build:
      context: docker
      dockerfile: shadowsocks.Dockerfile
    container_name: shadowsocks-warp
    network_mode: service:warp-shadowsocks
    volumes:
      - ./Volumes/shadowsocks-warp:/etc/shadowsocks-rust
    restart: always
    depends_on:
      - warp-shadowsocks

  gost:
    image: gogost/gost
    container_name: gost
    entrypoint: ["gost"]
    command: ["-C", "/etc/gost/gost.yaml"]
    volumes:
      - ./Volumes/gost:/etc/gost
    restart: always
    networks:
      - proxy
    depends_on:
      - warp-gost

  warp-gost:
    image: cloudflare-warp-gost
    build:
      context: docker
      dockerfile: warp-gost.Dockerfile
    container_name: warp-gost
    mem_reservation: 128m
    mem_limit: 320m
    volumes:
      - ./Volumes/warp-gost:/var/lib/cloudflare-warp
    restart: always
    networks:
      - proxy

networks:
  proxy:
